config/routes.rb
Rails.application.routes.draw do
 
  resources :sales
  require 'sidekiq/web' 
  mount Sidekiq::Web, at: "/sidekiq"
 root 'home#home'
  resources :products
  resources :employes
  resources :customers
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'categories/index', to: 'categories#index'
  get 'categories/data', to: 'categories#data'
  post 'categories/upload', to: 'categories#upload'
  post 'categories/destroy', to: 'categories#destroy'
  get 'get/customers/:id', to: 'customers#getCustomer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :sales
    validates :name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
    message: "solo permite letras" }
    validates :last_name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
    message: "solo permite letras" }
    validates :telephone, :presence => true, format: { with: /\A\d+\z/,
    message: "Solo se permite numeros"}
    validates :address, :presence => true

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :set_customer, only: %i[ show edit update destroy ]
  def index
    @customers=Customer.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "clientes: #{@customers.count}", template: "customers/index.html.erb", layout: 'pdf'   # Excluding ".pdf" extension.
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "clientes id: #{@customer.id}", template: "customers/customer.html.erb", layout: 'pdf'   # Excluding ".pdf" extension.
      end
    end
  end
  def getCustomer
    @customers=Customer.where(id: params[:id]).all
    render json:  @customers
  end

  def new
    @customer=Customer.new
  end

  def create
    @customer=Customer.new(customer_params)

    if @customer.save
      redirect_to @customer, notice: "El cliente fue creado con éxito"
    else
     render :new
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
     redirect_to @customer, notice: "Cliente fue actualizado con éxito" 
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_url, notice: "El cliente fue eliminado con éxito"
  end

  private 
  def set_customer
    @customer=Customer.find(params[:id])
  end
  
  def customer_params
    params.require(:customer).permit(:name, :last_name, :telephone, :address, :state)
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class="container">
<div class="row">
<div class="col-8">
<div class="card">
<div class="card-body">
<%= form_with(model: customer, id: 'customer') do |form| %>


  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "errores") %> prohibió que este cliente se guarde:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="input-group mb-3">
    <%= form.label :cedula, class: 'input-group-text' %>
    <%= form.text_field :cedula, class: 'form-control' %>
    
  </div>

  <div class="input-group mb-3">
    <%= form.label :name, class: 'input-group-text' %>
    <%= form.text_field :name, class: 'form-control' %>
    
  </div>
 

  <div class="input-group mb-3">
    <%= form.label :last_name, class: 'input-group-text' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :telephone, class: 'input-group-text' %>
    <%= form.text_field :telephone, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :address, class: 'input-group-text' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :state, class: 'input-group-text' %>
    <%= form.check_box :state, class: 'form-control' %>
  </div>
  

  <div class="actions">
    <%= form.submit class: 'btn btn-info text-white' %>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/customers/customer.html.erb
PDF generado:
<%= Time.zone.now%>

<p>
<strong>Nombre: </strong>
<%= @customer.name%>
</p>
<p>
<strong>Apellido(s): </strong>
<%= @customer.last_name%>
</p>
<p>
<strong>Telefono: </strong>
<%= @customer.telephone%>
</p>
<p>
<strong>Direccion: </strong>
<%= @customer.address%>
</p>

app/views/customers/edit.html.erb
<% @title="Clientes" %>
<div class="container mt-4 ">
<div class="row">
<div class="col-8">

<div class="card-header bg-info ">
<h3 class=" text-white text-center">Editar Cliente</h3>
</div>
</div>
</div>
</div>

<%= render 'form', customer: @customer %>
<div class="container">
<%= link_to 'Detalle ', @employe, class: 'text-white ms-3 btn btn-info' %> |
<%= link_to 'Volver', employes_path, class: 'ms-3 btn btn-danger' %>
</div>

app/views/customers/index.html.erb
<% @title="Clientes" %>
<div class="container">


<h1 class="text-center">Clientes</h1>
<%= link_to 'Nuevo Cliente', new_customer_path, class:'btn btn-info text-white btn-se' %>
<%= link_to 'Pdf', customers_path(format: :pdf), class: 'btn btn-info text-white btn-se' %>
<table class="table table-borderlesss">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido(s)</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Estado</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.telephone %></td>
        <td><%= customer.address %></td>
        <td><%= customer.state== true ? 'Activo': 'Inactivo' %></td>
        <td><%= link_to 'Pdf', customer_path(customer, format: :pdf), class: 'btn btn-info text-white btn-se' %></td>
        <td><%= link_to 'Detalle', customer, class: 'btn btn-info text-white btn-se' %></td>
        <td><%= link_to 'Editar', edit_customer_path(customer), class: 'btn btn-warning text-white btn-se'  %></td>
        <td><%= link_to 'Eliminar', customer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white btn-se'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/customers/new.html.erb
<% @title="Clientes" %>
<div class="container mt-4 ">
<div class="row">
<div class="col-8">

<div class="card-header bg-info ">
<h3 class=" text-white text-center">Nuevo Cliente</h3>
</div>
</div>
</div>
</div>

<%= render 'form', customer: @customer %>
<div class="container">
<%= link_to 'Back', customers_path, class: 'ms-3 btn btn-danger' %>
</div>

app/views/customers/show.html.erb
<% @title="Clientes" %>
<div class="container my-4">
<div class="row">
<div class="col-8">
<div class="card">
<div class="card-header bg-info">
<h3 class=" text-white text-center">Detalle al cliente <%=@customer.id%></h3>
</div>
<div class="card-body">



<p>
  <strong>Nombre:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @customer.telephone %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @customer.state %>
</p>


<%= link_to 'Editar', edit_customer_path(@customer), class: 'btn btn-warning text-white' %> |
<%= link_to 'Volver', customers_path, class: 'btn btn-danger text-white' %>
</div>
</div>
</div>
</div>
</div>