config/routes.rb
Rails.application.routes.draw do
 
  resources :sales
  require 'sidekiq/web' 
  mount Sidekiq::Web, at: "/sidekiq"
 root 'home#home'
  resources :products
  resources :employes
  resources :customers
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'categories/index', to: 'categories#index'
  get 'categories/data', to: 'categories#data'
  post 'categories/upload', to: 'categories#upload'
  post 'categories/destroy', to: 'categories#destroy'
  get 'get/customers/:id', to: 'customers#getCustomer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :product 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_categories, only: %i[ index data ]

    def index
        if @categories.length > 0
            redirect_to categories_data_path
        else
            render :index
        end
    end
    def data
    end
    def upload
        csv_file = File.join Rails.root, 'db', 'sharks.csv'
        AddCategoryWorker.perform_async(csv_file)
        redirect_to categories_data_path, notice: 'Informacion de la categoria cargada'
    end
    def destroy
        RemoveCategoryWorker.perform_async
        redirect_to customers_path
    end
    private
    def set_categories
        @categories=Category.all
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/data.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>


<div class="table-responsive">
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |ca| %>
      <tr>
        <td><%= ca.name %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

  <%= form_tag categories_destroy_path do %>
  <%= submit_tag "Delete Endangered Sharks" %>
  <% end %>

  <br>

<%= link_to 'New Categorie', new_customer_path, :class => "btn btn-primary btn-sm" %> 

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias  </h1>


<br>

  <%= form_tag categories_upload_path do %>
  <%= submit_tag "Importar categorias" %>
  <% end %>

  <br>

<%= link_to 'Nueva categoria', new_customer_path, :class => "btn btn-primary btn-sm" %> 