config/routes.rb
Rails.application.routes.draw do
 
  resources :sales
  require 'sidekiq/web' 
  mount Sidekiq::Web, at: "/sidekiq"
 root 'home#home'
  resources :products
  resources :employes
  resources :customers
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'categories/index', to: 'categories#index'
  get 'categories/data', to: 'categories#data'
  post 'categories/upload', to: 'categories#upload'
  post 'categories/destroy', to: 'categories#destroy'
  get 'get/customers/:id', to: 'customers#getCustomer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employe.rb
class Employe < ApplicationRecord
    validates :name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
        message: "solo permite letras" }
        validates :last_name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
        message: "solo permite letras" }
        validates :telephone, :presence => true, format: { with: /\A\d+\z/,
        message: "Solo se permite numeros"}
        validates :address, :presence => true
end

app/controllers/employes_controller.rb
class EmployesController < ApplicationController
  before_action :set_employe, only: %i[ show edit update destroy ]

  # GET /employes or /employes.json
  def index
    @employes = Employe.all
  end

  # GET /employes/1 or /employes/1.json
  def show
  end

  # GET /employes/new
  def new
    @employe = Employe.new
  end

  # GET /employes/1/edit
  def edit
  end

  # POST /employes or /employes.json
  def create
    @employe = Employe.new(employe_params)

    respond_to do |format|
      if @employe.save
        format.html { redirect_to @employe, notice: "Empleado fue creado con éxito" }
        format.json { render :show, status: :created, location: @employe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employes/1 or /employes/1.json
  def update
    respond_to do |format|
      if @employe.update(employe_params)
        format.html { redirect_to @employe, notice: "Empleado fue actualizado con éxito" }
        format.json { render :show, status: :ok, location: @employe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employes/1 or /employes/1.json
  def destroy
    @employe.destroy
    respond_to do |format|
      format.html { redirect_to employes_url, notice: "Empleado fue eliminado con  éxito" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employe
      @employe = Employe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employe_params
      params.require(:employe).permit(:name, :last_name, :age, :telephone, :salary, :cargo)
    end
end

app/helpers/employes_helper.rb
module EmployesHelper
end

app/views/employes/_form.html.erb
<div class="container">
<div class="row">
<div class="col-8">
<div class="card">
<div class="card-body">
<%= form_with(model: employe, id: "empleado") do |form| %>


  <% if employe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employe.errors.count, "error") %> prohibited this employe from being saved:</h2>

      <ul>
        <% employe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  
  <% end %>
  
  <div class="input-group mb-3">
    <%= form.label :name, class: 'input-group-text' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :last_name, class: 'input-group-text' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :age, class: 'input-group-text' %>
    <%= form.number_field :age, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :telephone, class: 'input-group-text' %>
    <%= form.text_field :telephone, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :salary, class: 'input-group-text' %>
    <%= form.text_field :salary, class: 'form-control' %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :cargo, class: 'input-group-text' %>
    <%= form.text_field :cargo, class: 'form-control' %>
  </div>
  

  <div class="actions">
    <%= form.submit class: 'btn btn-info text-white' %>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/employes/edit.html.erb
<% @title="Empleados" %>
<div class="container mt-4 ">
<div class="row">
<div class="col-8">

<div class="card-header bg-info ">
<h3 class=" text-white text-center">Editar Empleado</h3>
</div>
</div>
</div>
</div>

<%= render 'form', employe: @employe %>
<div class="container">
<%= link_to 'Detalle ', @employe, class: 'text-white ms-3 btn btn-info' %> |
<%= link_to 'Volver', employes_path, class: 'ms-3 btn btn-danger' %>
</div>

app/views/employes/index.html.erb
<% @title="Empleados" %>

<div class="container">


<h1 class="text-center">Empleados</h1>
<%= link_to 'Nuevo Empleado', new_employe_path, class:'btn btn-info text-white' %>
<table class="table table-borderlesss">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Telephone</th>
      <th>Salary</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employes.each do |employe| %>
      <tr>
        <td><%= employe.name %></td>
        <td><%= employe.last_name %></td>
        <td><%= employe.age %></td>
        <td><%= employe.telephone %></td>
        <td><%= employe.salary %></td>
        <td><%= employe.cargo %></td>
        <td><%= link_to 'Detalle', employe, class: 'btn btn-info text-white' %></td>
        <td><%= link_to 'Editar', edit_employe_path(employe), class: 'btn btn-warning text-white'  %></td>
        <td><%= link_to 'Eliminar', employe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/employes/new.html.erb
<% @title="Empleados" %>
<div class="container mt-4 ">
<div class="row">
<div class="col-8">

<div class="card-header bg-info ">
<h3 class=" text-white text-center">Nuevo Empleado</h3>
</div>
</div>
</div>
</div>

<%= render 'form', employe: @employe %>
<div class="container">
<%= link_to 'Back', employes_path, class: 'ms-3 btn btn-danger' %>
</div>

app/views/employes/show.html.erb
<% @title="Empleados" %>
<div class="container my-4">
<div class="row">
<div class="col-8">
<div class="card">
<div class="card-header bg-info">
<h3 class=" text-white text-center">Detalle del empleado <%=@employe.id%></h3>
</div>
<div class="card-body">



<p>
  <strong>Name:</strong>
  <%= @employe.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employe.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employe.age %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @employe.telephone %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employe.salary %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @employe.cargo %>
</p>

<%= link_to 'Editar', edit_employe_path(@employe), class: 'btn btn-warning text-white' %> |
<%= link_to 'Volver', employes_path, class: 'btn btn-danger text-white' %>
</div>
</div>
</div>
</div>
</div>