config/routes.rb
Rails.application.routes.draw do
 
  resources :sales
  require 'sidekiq/web' 
  mount Sidekiq::Web, at: "/sidekiq"
 root 'home#home'
  resources :products
  resources :employes
  resources :customers
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'categories/index', to: 'categories#index'
  get 'categories/data', to: 'categories#data'
  post 'categories/upload', to: 'categories#upload'
  post 'categories/destroy', to: 'categories#destroy'
  get 'get/customers/:id', to: 'customers#getCustomer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :product 
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :sales
    validates :name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
    message: "solo permite letras" }
    validates :last_name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
    message: "solo permite letras" }
    validates :telephone, :presence => true, format: { with: /\A\d+\z/,
    message: "Solo se permite numeros"}
    validates :address, :presence => true

end

app/models/employe.rb
class Employe < ApplicationRecord
    validates :name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
        message: "solo permite letras" }
        validates :last_name, :presence => true, format: { with: /\A[a-zA-Z]+\z/,
        message: "solo permite letras" }
        validates :telephone, :presence => true, format: { with: /\A\d+\z/,
        message: "Solo se permite numeros"}
        validates :address, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :categories    
end

app/models/user.rb
class User < ApplicationRecord
     # adds virtual attributes for authentication
     has_secure_password
     # validates email
     validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/employes_controller.rb
class EmployesController < ApplicationController
  before_action :set_employe, only: %i[ show edit update destroy ]

  # GET /employes or /employes.json
  def index
    @employes = Employe.all
  end

  # GET /employes/1 or /employes/1.json
  def show
  end

  # GET /employes/new
  def new
    @employe = Employe.new
  end

  # GET /employes/1/edit
  def edit
  end

  # POST /employes or /employes.json
  def create
    @employe = Employe.new(employe_params)

    respond_to do |format|
      if @employe.save
        format.html { redirect_to @employe, notice: "Empleado fue creado con éxito" }
        format.json { render :show, status: :created, location: @employe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employes/1 or /employes/1.json
  def update
    respond_to do |format|
      if @employe.update(employe_params)
        format.html { redirect_to @employe, notice: "Empleado fue actualizado con éxito" }
        format.json { render :show, status: :ok, location: @employe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employes/1 or /employes/1.json
  def destroy
    @employe.destroy
    respond_to do |format|
      format.html { redirect_to employes_url, notice: "Empleado fue eliminado con  éxito" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employe
      @employe = Employe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employe_params
      params.require(:employe).permit(:name, :last_name, :age, :telephone, :salary, :cargo)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

    def index
      @products = Product.all
    end

    def show
    end


    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)

      
        if @product.save
          redirect_to @product, notice: "Producto creado con exito." 
          
        else
          render :new
        end
      
    end


    def edit
    end

      def update
      
        if @product.update(product_params)
          redirect_to @product, notice: "Producto actualizado con exito" 
        else
          render :edit
        end
   
    end

    def destroy
      @product.destroy
      
    redirect_to products_url, notice: "Producto eliminado con exito" 
    
      end
  

    private
      
      def set_product
        @product = Product.find(params[:id])
      end

      
      def product_params
        params.require(:product).permit(:name, :description, :stock, :price, :state)
      end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new;
     end
    def create
        user=User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
        redirect_to customers_path, notice: 'Conectado con éxito'
    else
        flash.now[:alert] = 'Correo o Clave invalidos'
        render :new
        end
    end
    def destroy
        # deletes user session
        session[:user_id] = nil
        redirect_to customers_path, notice: 'Desconectado'
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/employes_helper.rb
module EmployesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'sales' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand fw-bold" href="#">Game <span class="text-danger">Store</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Inicio</a>
        </li>
        <li class="nav-item">
         
          <%= link_to 'Empleados', employes_path, class: 'nav-link'%> 
        </li>
        <li class="nav-item">
         <%= link_to 'Clientes', customers_path, class: 'nav-link'%> 
        </li>
        <li class="nav-item">
         <%= link_to 'Productos', products_path, class: 'nav-link'%> 
        </li>
       
      </ul>
      <ul class="navbar-nav ">
      <% if Current.user %>
      <li class="nav-item">
       <strong class="nav-link">Bienvendido: <%= Current.user.email %></strong> 
      </li> 
       <li class="nav-item">
         
          <%= link_to 'Cerrar Sesion', logout_path, method: :delete, class: 'nav-link'%> 
        </li>
        <% else %>
         <li class="nav-item">
         
          <%= link_to 'Login', sign_in_path, class: 'nav-link'%> 
        </li>
         <li class="nav-item">
         
          <%= link_to 'Registro', sign_up_path, class: 'nav-link'%> 
        </li>  
         <%end%> 
            </ul> 
    </div>
  </div>
</nav>
    <%= yield %>
     <%if notice.present?%>
    <script type="text/javascript">
      
      Swal.fire(
  'Correcto!',
  '<%=notice%>',
  'success'
)
    </script>
  <%end%> 
     <%if alert.present?%>
    <script type="text/javascript">
      
      Swal.fire(
  'Oops!',
  '<%=alert%>',
  'error'
)
    </script>
  <%end%> 
<button id="boton">Mostrar</button>
  </body>
</html>
<!--<script>
$().ready(()=>{
$.validator.addMethod("soloLetras", function (value, element) {
    var pattern = /^[a-zA-Z ]+$/;
    return this.optional(element) || pattern.test(value);
  }, "");
  $.validator.addMethod("soloNumeros", function (value, element) {
    var pattern = /[0-9]+/;
    return this.optional(element) || pattern.test(value);
  }, "El campo solo debe contener numeros");
   $("#customer").validate({
     rules:{
       "customer[name]": {required: true, soloLetras: true},
       "customer[last_name]": {required: true, soloLetras: true},
       "customer[telephone]": {required: true, soloNumeros: true, minlength: 7, maxlength: 10},
       "customer[address]": {required: true}


     },
     messages:{
       "customer[name]": {required: 'El campo nombre no puede estar vacio', soloLetras: 'El campo debe contener solo letras'},
        "customer[last_name]": {required: 'El campo apellidos no puede estar vacio', soloLetras: 'El campo debe contener solo letras'},
         "customer[telephone]": {required: 'El campo Telefono no puede estar vacio', soloNumeros: 'El campo debe contener solo numeros', minlength: 'El campo debe tener como minimo 7 numeros', maxlength: 'El campo  no puede tener mas de 10 numeros' },
         "customer[address]": {required: "El campo direccion no puede estar vacio"}
     }
   });  
})
  
 
</script>-->

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>